### ISSUE TITLE
Is the use `gitDir.findOrCreateChildData(..., "machete")` rather than `GitVfsUtils#getMacheteFile` expected?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1141]
See `com.virtuslab.gitmachete.frontend.actions.toolbar.OpenMacheteFileAction#actionPerformed`:

```java
val macheteFile = WriteAction.compute(() -> Try
        .of(() -> gitDir.findOrCreateChildData(/* requestor */ this, /* name */ "machete"))
.....
```

This is somewhat suspicious... I'd rather expect machete file path to be resolved uniformly via a dedicated util class, `com.virtuslab.gitmachete.frontend.vfsutils.GitVfsUtils` 🤔 

TBD if that was intentional, and if there're any other places like that (AFAICS there aren't).

**Comment by MaciejG604** [comment]
Turns out this line was first introduced here [commit d9d75741](https://github.com/VirtusLab/git-machete-intellij-plugin/commit/d9d75741), by then GitVfsUtils was not around as it was introduced in [commit da82e682](https://github.com/VirtusLab/git-machete-intellij-plugin/commit/da82e682). So probably it has just been overlooked during code review.
