### ISSUE TITLE
Add Javadoc comments for our custom annotations

### ISSUE THREAD

**Issue by LukaszKontowski** [VirtusLab/git-machete-intellij-plugin#1231]
Each annotation defined in our repository should have a Javadoc comment. This Javadoc should explain, when such annotation should be used etc.

**Comment by PawelLipski** [comment]
:pepepanic:

**Comment by mkondratek** [comment]
@PawelLipski we can close this one, right? 

(y are they not closing atomagically with the pr? :thinkinggggg:)

**Comment by PawelLipski** [comment]
:yes: we can close

The issues only close once all the linked PRs are merged to **default** branch, i.e. `master` for this repo.

Ideally, GitHub would have two separate settings:
1. the branch to which you need to merge all linked PRs for the issue to close (that would be `develop` for us)
2. the branch from which README is taken (that would be `master`).

Given that we need to select just one for both 1+2... I'm choosing 2. over 1. (so that only the released stuff is displayed in README)
