### ISSUE TITLE
Branch names containing HTML tags are incorrectly formatted

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#1242]
<details>
<summary>Examples from Slide In action scope</summary>
<img width="428" alt="Screenshot 2022-10-11 at 13 30 14" src="https://user-images.githubusercontent.com/19799111/195083121-6cd8a6bb-7d31-4d9c-a989-a79848f31f63.png">
<img width="841" alt="Screenshot 2022-10-11 at 13 30 53" src="https://user-images.githubusercontent.com/19799111/195083128-98d2a582-047c-4de9-82c6-71a75cdacba5.png">
<img width="812" alt="Screenshot 2022-10-11 at 13 31 10" src="https://user-images.githubusercontent.com/19799111/195083132-a5066e17-655a-43c3-a82b-8c6690f5cd79.png">
<img width="351" alt="Screenshot 2022-10-11 at 13 31 53" src="https://user-images.githubusercontent.com/19799111/195083135-77712144-a378-433f-b459-bffddcc0d2ab.png">
<img width="427" alt="Screenshot 2022-10-11 at 13 32 02" src="https://user-images.githubusercontent.com/19799111/195083136-1ee472a6-1fc3-4629-9f01-33f2eceb6a47.png">
</details>

Branch names containing HTML tags (which is surprisingly legal) are incorrectly formatted (which is not a surprise).
The provided examples come from the Slide In action scope, but there are others to be defined and fixed (e.g. Override Fork Point dialog).

Suggested solution:
`org.apache.commons.text.StringEscapeUtils.escapeHtml4`

**Comment by PawelLipski** [comment]
Lemme assign to @MaciejG604 as a filler-up task for while he might be blocked in his new project

**Comment by PawelLipski** [comment]
Within the scope of this task, let's also use the existing `@Tainted`/`@Untainted` mechanism to detect such places automatically (as much as possible... we're limited by using Kotlin (where Checker doesn't operate) for dialogs, alas)

**Comment by PawelLipski** [comment]
>  `org.apache.commons.text.StringEscapeUtils.escapeHtml4`

We've somehow already got that on classpath... probably as dependency of IntelliJ itself

**Comment by PawelLipski** [comment]
Already done by @mkondratek :p

**Comment by mkondratek** [comment]
No! See the comment there 😆

**Comment by MaciejG604** [comment]
Worth mentioning: 
Things that are managed by `git4idea` will keep being displayed wrong and I don't really see any good solution to that. It is because some `git4idea` functions require you to pass the name of the branch which they later validate against the repo.

So we could either accept this or name all branches in the repo with html-escaped strings, but this has a major drawback - when a user switches back to using git from CLI all their branches will have unexpected names.

Examples:
![image](https://user-images.githubusercontent.com/61919032/197523626-a5ee2c49-af5b-4679-8e2e-103cd47f56d9.png)
![image](https://user-images.githubusercontent.com/61919032/197523680-d3697670-236b-437a-baa2-4a1693939fc0.png)
![image](https://user-images.githubusercontent.com/61919032/197523726-e376aad6-fd63-488c-9833-67a5fd641fe6.png)

Branch seen here as `&lt;html&gt;&lt;b&gt;TEST_33&lt;/b&gt;&lt;/html&gt;` could be created by a user as </br>`<html><b>TEST_33</b></html>`, we can then display it always as the user requested, but undearneath its name in git needs to be `&lt;html&gt;&lt;b&gt;TEST_33&lt;/b&gt;&lt;/html&gt;` for `git4idea` to work properly.

Changing the underlaying branch name is unacceptable and definitely not worth the HTML tag support.
