### ISSUE TITLE
For reading/writing branch layout, shouldn't we use VFS rather than plain java.(n)io?

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#1303]
I'm not sure if we should just use plain `write` (which uses some plain `java.(n)io` under the hood)... this should probably happen via VFS. Same with reading the branch layout file. Lemme open an issue...

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1301#discussion_r1004842922_

**Comment by PawelLipski** [comment]
TBD what are the consequences of either approach.

**Comment by PawelLipski** [comment]
Looks there are some uses of Document API in our codebase already, see e.g. `com.virtuslab.gitmachete.frontend.file.MacheteFileUtils#saveDocument`

**Comment by mkondratek** [comment]
![SmartSelect_20221026-124232_Chrome](https://user-images.githubusercontent.com/19799111/198006341-b5ecd182-1e6e-425d-9de0-bad34159434b.jpg)

**Comment by PawelLipski** [comment]
> ![SmartSelect_20221026-124232_Chrome](https://user-images.githubusercontent.com/19799111/198006341-b5ecd182-1e6e-425d-9de0-bad34159434b.jpg)

Curious. is this move so _memogenic_ outside of 🇵🇱 ? 🤔

**Comment by mkondratek** [comment]
https://www.reddit.com/r/dankmemes/comments/jp7ry4/asterix_obelix_mission_cleopatra_is_the_best/

And as it is a french movie there are some french memes. 
See https://fr.memedroid.com/memes/tag/mission+cleopatre.
E.g.
![5f06daa84ae0e](https://user-images.githubusercontent.com/19799111/198011485-68dabc63-cda6-4871-b6e4-f78aa32b6b93.jpeg)

Which is (I may be wrong, I do not speak french):
- a cat when I want to stroke it (pol. _pogłaskać_)
- a lion does not associate with a cockroach (in polish translation of the movie it's "Lew nie sprzymierza się z kojotem))
- a cat when I shake the bag of kibble (pol. _krokiety_?)
- Comrades! (pol. _towarzysze_)

**Comment by MaciejG604** [comment]
I've done some research, while not using the VFS for file I/O operations does not actively hurt the plugin it might lead to unexpected problems (can't find the source for that atm). So switching to VFS api could be done out of cautiousness, This should happen together with using `Write/ReadActions` since the API throws if functions are called outside of such `Action`.
We'll also need a little refactor to our backend tests to mock `VirtualFileManager`, but that should not be a problem.

When it comes to the choice of API I think VFS API [[1]](https://github.com/JetBrains/intellij-community/blob/idea/222.3739.54/platform/core-api/src/com/intellij/openapi/vfs/VfsUtilCore.java) [[2]](https://github.com/JetBrains/intellij-community/blob/idea/222.3739.54/platform/analysis-api/src/com/intellij/openapi/vfs/VfsUtil.java) supports enough operations (load/copy/save) so there's no need to add the [Document API](https://github.com/JetBrains/intellij-community/blob/idea/222.3739.54/platform/core-impl/src/com/intellij/util/DocumentUtil.java).
Apart from that I am not really sure what are the correct circumstances to use VFS or Document. If you know something more about it please share as the documentation is quite short and not very informative when it comes to practical tips.

**Comment by PawelLipski** [comment]
Looks that this one can be closed...
