### ISSUE TITLE
Derive git hooks directory location according to the spec

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#289]
`git config core.hooksPath` also needs to be taken into account, see `git help hooks`. Currently we're just always looking into `$GITDIR/hooks` for `machete-status-branch` and `machete-pre-rebase`.

**Comment by DcortezMeleth** [comment]
I would be happy to help with this issue, but I'm going to need help with 2 things to start off.

According to docs, core.hooksPath is supported since Git 2.9.0, released on 13 Jun 2016. Do we need to check if we try use this variable in older versions? Or can we safely assume that user should already have a more recent version? 

Second topic is more technical. Is it possible to write some kind of tests to test this behaviour? I didn't see tests for classes that probably are going to change but I may be looking in wrong places or test for those classes wasn't necessary.

**Comment by PawelLipski** [comment]
Hey, nice to see you here ^^

I think it's unlikely that both user will have git <= 2.9 AND `core.hooksPath` config value set, so I wouldn't care much :)

Whoops no, due to constrained time/budget we limited the tests to the most critical/error-prone cases, but added a lot of automated checks (like Checker Framework, ArchUnit and IntelliJ's platform own compatibility checks)... in the long run, it's actually proven pretty sustainable, there were relatively few discovered bugs, and a very few critical released bugs in total. Currently we do run UI (end-to-end) tests (under `uiTests/`), and unit tests for non-trivial parts of the codebase (mostly in `backendImpl/src/test`)

**Comment by DcortezMeleth** [comment]
One more thing.
As it is in fact my very first contribution to os in form of pr, could you guide my how flow should look?
I mean all fork/rebase/pr related things.

**Comment by PawelLipski** [comment]
Actually... let me grant you write permissions in the repo, no need for you to make an extra fork :)

Other than that, we'd strongly recommend the practices outlined in https://slides.com/plipski/git-machete, 1.1 + 1.2 -> small PRs, linear history... although I'm aware that for a single PR this might not matter as much :)

**Comment by PawelLipski** [comment]
Hi @DcortezMeleth... any updates on this one? ;)
