### ISSUE TITLE
Pulling the current branch does NOT update the working tree

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#424]
HEAD gets updated, but not working directory or index (so as with `git reset --soft`), and this is not what user would expect from a pull-like action. This is probably the result of how git-fetching the current branch operates.

**Comment by micpiotrowski** [comment]
Probably related to this (effect of this issue): When I was on root branch (if it even is important) I invoked `pull` action from toolbar and this rather something like `fetch` than `pull`. When I repeated `pull` action (this time from context menu) then true `pull` was done.

**Comment by PawelLipski** [comment]
Your comment @micpiotrowski probably refers to an older version of the plugin as for some time there's no longer any pull action in the left-side toolbar. Anyway, it might return to toolbar once #427 is addressed. Anyway, let's first address the original issue with the  working tree first.

**Comment by mkondratek** [comment]
We could use the `Pull Dialog` for the current branch case:

![image](https://user-images.githubusercontent.com/19799111/87243802-261f8000-c439-11ea-9c39-b487b358a21e.png)

**Comment by PawelLipski** [comment]
@mkondratek would be nice if the pull operation we provide is **fast-forward-only** (at least by default) - will it be possible with the above dialog?

**Comment by mkondratek** [comment]
whoops, the checkbox that we can see above `No fast forward` allows switching between the default `--ff` and `--no-ff`

furthermore, the dialog will possibly change with the 202.* :confused: 
A look from 2020.2 BETA:

![image](https://user-images.githubusercontent.com/19799111/87309247-a1a62d80-c51c-11ea-9e9c-a4e63f36ceb6.png)

**Comment by PawelLipski** [comment]
Heh, looks that JB is basically changing the existing git4idea dialogs into "command line builders" xD

**Comment by mkondratek** [comment]
My investigation has proven that the dialog will actually change. Hence we should not depend on it.

Reimplementation (less stable solution, more work) is not necessary since we do know all the options & params to perform `pull --ff-only` on the current branch. 

Ofc we could disable the pull for the current branch (some solution, stable & easy).

Going a little lower we can use `GitLineHandler` (more stable solution, not so hard).
Even though the logic around it seems to be a bit complex I think that this is the best option.

The draft for the third one: #438
