### ISSUE TITLE
Horizontal content overflow in GraphTableDialog

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#491]
For now content of graph table in `GraphTableDialog` is hidden when it overflows horizontally and there is no horizontal scrollbar in that situation.
![image](https://user-images.githubusercontent.com/3383210/89320246-8775f000-d681-11ea-8a73-924f1faee642.png)

**Comment by mkondratek** [comment]
I think that the problem lies elsewhere (at least some significant part of it). IMHO we ought not to list commits here.
- listing commits is an additional feature (not default) 
- the idea behind Git Machete is to focus on branches (not commits)
- commits messages can be long (with potential fork point indication the row gets very long)
- branches can contain a lot of commits
- AFAIK it is not consistent with git machete CLI (@PawelLipski, can you confirm that?)
- my personal experience shows that in most of the time the commits listing is off cause:
    - it makes the graph less transparent (hard to read)
    - it is inconvenient in use (lots of scrolling required, our actions are based on branches)

Ofc the above arguments are disputable (with CLI consistency and esp. my personal experience).

Theoretically, we could add toggle listing commits checkbox to the potential preceding "discover set up dialog" (or settings) but I would not use it as default.

**Comment by mkondratek** [comment]
Back to the issue (even though we will not show the commits the branches can still exceed the given width of graph table)...

<details>
<summary>"Handling" examples</summary>

## (Our) Discovered branch layout Dialog

![image](https://user-images.githubusercontent.com/19799111/89618674-e5c2ee80-d88c-11ea-9d46-d9d47a01196d.png)

## Interactive Rebase Dialog

![image](https://user-images.githubusercontent.com/19799111/89618619-cb891080-d88c-11ea-8c78-8eb5d066a274.png)

## VCS Log Graph Table

![image](https://user-images.githubusercontent.com/19799111/89618853-363a4c00-d88d-11ea-9513-57cc994995bb.png)

</details>

My point is that it is already handled (probably not ideally).
We should ask us a question: 
Isn't THEIR approach right?


## The danger I see behind the horizontal scrolling:

![image](https://user-images.githubusercontent.com/19799111/89619839-f70cfa80-d88e-11ea-8022-0be06f79af3b.png)

Another point is that we consider too extensive branch layouts (and too long commits msges) as a bad and uncommon practice, right?
ability to see one or two too long rows <<< clean and simple UI (one is still able to see the long line!)

---

I am not sure about how much work is required to add the horizontal scrolling yet. Most likely it is easily doable so we will be able to see that my doubts are justified.

**Comment by PawelLipski** [comment]
I do agree that:
1. adding horizontal scrolling, esp. if it's not just a matter of switching one boolean flag, is kinda overkill if the sole purpose is just making `fork point?` segment more visible
1. in fact, including `fork point?` segment at all in the discovered layout is kinda redundant/confusing/obfuscating the really important pieces

**Comment by PawelLipski** [comment]
TBH I'm not sure whether including or not including the commits by default is a better choice... I myself don't run `discover` very often: it's critical for onboarding new users smoothly but near-useless for the folks who simply use git-machete all the time :trollface:

**Comment by PawelLipski** [comment]
Both have `asses and jacks` aka `zady i walety`:
* listing commits makes it easier for the fresh user to understand what's happening, esp. if they don't really remember what was the specific purpose of each involved branch
* not listing commits makes the overall picture more clear since the amount of detail is reduced

**Comment by PawelLipski** [comment]
> AFAIK it is not consistent with git machete CLI (@PawelLipski, can you confirm that?)

`git machete discover` has `--list-commits` flag which would indicate we could have a toggle list commits button... but again, I don't think that adding that flag (and choosing that it's off by default) was a very conscious/thought-over decision on my part ;D

**Comment by PawelLipski** [comment]
> my personal experience shows that in most of the time the commits listing is off cause:

I'd say I usually turn listing commits on in the plugin when doing some side-effecting actions, esp. rebase (so that I see upfront what commits are going to be rebased)

**Comment by PawelLipski** [comment]
Okay... my impression now that I'm fixing #516 is actually that no commits should be displayed... otherwise we might end up with basically 90+% of the table filled up with the commits in some unfortunate cases (it's hard to say now that we don't have much feedback what's gonna happen in the actual users' repos), and that's gonna make a baaaad impression :/

**Comment by mkondratek** [comment]
piggybacking on #495 then
