### ISSUE TITLE
Investigate if the Ctrl+Shift+O reload button can be made more deterministic

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#548]
Feedback from @MichalBednarz (actually two separate issues):

- [ ] _Added a new branch called machete-test first to the local repo then to the ./git/machete file by hand. Can’t see the refresh button to refresh the plugin view. It started to work eventually but it has to be clicked twice._
- [ ] _The trigger button sometimes appears for me as a hybrid one - for sbt and machete though the sbt build config hasn’t been changed._

I'm aware the above might hard to resolve (esp. the 2nd issue)... let's spend ~1h to check if anything can be done about the 1st one at least :detective:

**Comment by mkondratek** [comment]
## Investigation
My investigation led to the following class:
`com.intellij.openapi.externalSystem.autoimport.ProjectSettingsTracker.ProjectSettingsListener`

![image](https://user-images.githubusercontent.com/19799111/91989181-7d9ee580-ed30-11ea-8336-7570edfa3929.png)

For some reason, `hasChanges` is false here on some changes to the file (adding/removing space in particular).

The problem seems to be the fact that it is not us who decide what is the actual meaningful change.
Sadly, I see no option to change it.

## Possible solution
We could implement the `FilesChangesListener` for our own service.
That would mean the drop of the whole `frontendExternalSystem` module.
Custom implementation of floating toolbar show/hide logic will be required.
We could start from `com/intellij/openapi/externalSystem/autoimport/AutoImportProjectTracker.kt#updateProjectNotification`.

**Comment by PawelLipski** [comment]
=> #561 for an actual implementation task
