### ISSUE TITLE
Machete complains about branches not belonging to local repository after deleting them locally

### ISSUE THREAD

**Issue by ahus1** [VirtusLab/git-machete-intellij-plugin#709]
### Observed

When deleting a local branch outside of Git Machete, it later complains that there are branches in the git machete file

### Expected

The Git machete file should be cleaned, at least when I click "refresh" in the Git Machete tab

## Steps to reproduce

* manually delete a local branch via standard IntelliJ tooling (click on branch overview, on lower right, choose local branch, right-click, delete)
* click "refresh" button in Git Machete
* Machete complains with a small popup "The following branches defined by machete file do not belong to the local repository..."

### Running environment
 - Git Machete plugin version: 0.8.2

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: Batch Scripts Support, PsiViewer, com.virtuslab.git-machete, CheckStyle-IDEA, EclipseCodeFormatter, YourKit Java Profiler 2020.7-b376 Integration, com.dubreuia, com.jetbrains.codeWithMe, org.sonarlint.idea, org.jetbrains.plugins.vue, org.intellij.scala, PlantUML integration, org.asciidoctor.intellij.asciidoc

**Comment by PawelLipski** [comment]
Thanks for reporting the issue (with such a detailed breakdown)!

Actually, a very similar issue has been raised in the CLI recently: https://github.com/VirtusLab/git-machete/issues/100, and this has been fixed in the CLI by adding a prompt `Skipping feature/foo, bugfix/bar which are not local branches (perhaps they have been deleted?). Slide them out from the definition file?`.

So, my suggestion here would be to analogically add a button/link to the mentioned popup (_The following branches defined by machete file do not belong to the local repository..._) that suggests sliding out the deleted branches, WDYT @ahus1?

We don't want to remove non-existent branches automatically to avoid surprises to the users, and distinguishing between deleted branches and just never-existing-ones might be troublesome :/

**Comment by mkondratek** [comment]
@ahus1 please note that if you intend to delete both the local branch and the branch entry (from the machete file), you can simply use **Slide Out** action from Git Machete graph table (Git Machete Tab) :slightly_smiling_face:

**Comment by ahus1** [comment]
@mkondratek there is a "Slide out" already in the "Git Machete" tab. But I didn't dare to try it, as the reference [blog post](https://medium.com/virtuslab/make-your-way-through-the-git-rebase-jungle-with-git-machete-e2ed4dbacd02) told me that it would rebase something. That scared me a bit, I just wanted to delete the two local branches, and would leave the remote branches as is. That's how I ended up in this situation.

**Comment by ahus1** [comment]
@PawelLipski: a popup would be ok, as this would keep me away from finding out which file to edit manually. 

Thinking about it it is only second-best. When I deleted the branch via the IDE a moment ago, why would Git Machete ask me to remove it also from the tree?

My context is that I'm looking for something to make it easier for not-so-technical writers to manage their content with Git. I want to give them a good simple start with Git, with a nice gradual learning curve. I'm currently giving git-machete a try to find out if this would be solving the Git onboarding issues. 

My personal background is that I'm the maintainer of the IntelliJ AsciiDoc plugin and want to allow people to manage AsciiDoc and Antora content in a smooth way within an IDE.

**Comment by PawelLipski** [comment]
> there is a "Slide out" already in the "Git Machete" tab. But I didn't dare to try it, as the reference blog post told me that it would rebase something. That scared me a bit, I just wanted to delete the two local branches, and would leave the remote branches as is. That's how I ended up in this situation.

Whoops okay, this is indeed an inconsistency b/w CLI and IntelliJ plugin (CLI: `slide-out` runs rebase on child branch, plugin: `Slide Out` does not run any rebase)... we'll take care to smooth that out so that it's clear from the docs.

>  as this would keep me away from finding out which file to edit manually.

Always the same file, `.git/machete` :) also, this could be opened in IntelliJ editor via `Open machete` button on the left-hand side:

![image](https://user-images.githubusercontent.com/3383210/108773162-3d415700-755e-11eb-8a61-f5d7e0c9730c.png)

But your point is valid, editing the file shouldn't be necessary for such a common scenario as deleting a branch.
Currently, this is realized by the `Slide Out` action... but probably could be fully automated 👇🏻

> Thinking about it, it is only second-best. When I deleted the branch via the IDE a moment ago, why would Git Machete ask me to remove it also from the tree?

Okay, we'll investigate if it's possible to somehow hook up to git branch deletion event in the IDE so that the slide-out from the tree will happen automatically :) probably the timeline will be that we'll add the `Slide out?` button to the popup first in the upcoming release, and then try to figure out how to slide-out automatically in deletion even without any user interaction.

> My context is that I'm looking for something to make it easier for not-so-technical writers to manage their content with Git. I want to give them a good simple start with Git, with a nice gradual learning curve. I'm currently giving git-machete a try to find out if this would be solving the Git onboarding issues.

Great to hear! pls let us know how it goes, even if the feedback is in the negative &mdash; i.e. if you deem git-machete NOT simple enough for non-tech ppl to start with, it'd be valuable to know what the obstacles were.

> My personal background is that I'm the maintainer of the IntelliJ AsciiDoc plugin and want to allow people to manage AsciiDoc and Antora content in a smooth way within an IDE.

I recall you/your plugin from IntelliJ Platform Slack (other than being an occasional user of this plugin, when a project I'm contributing to has AsciiDoc docs)... out of curiosity, how did you learn of git-machete? was it via that Slack?

**Comment by PawelLipski** [comment]
@ahus1 addressed via #714; will be released soon as v0.9.0

**Comment by PawelLipski** [comment]
Ok, a basic solution has been released some time ago (#710);
#711 is queued for the future
