### ISSUE TITLE
Mark the commit deemed as fork point

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#72]
Git Machete CLI marking:
![image](https://user-images.githubusercontent.com/19799111/74545467-321a1b00-4f49-11ea-9c82-14f3a931bf43.png)

**Comment by PawelLipski** [comment]
Related point: currently in case of yellow edge, the plugin only lists the commits until the fork point (exclusively). This is obviously incompatible with what this issue aims at since currently the plugin always skips the fork point from commit listing in case of yellow edge:

CLI:

![image](https://user-images.githubusercontent.com/3383210/82896308-0817c200-9f56-11ea-950f-e4ceb0ace60b.png)

but in plugin v0.4.0-10-SNAPSHOT+git.e6b0a6a:

![image](https://user-images.githubusercontent.com/3383210/82896369-254c9080-9f56-11ea-822c-8f979b15a426.png)
