### ISSUE TITLE
Opening the Machete File Editor changes global editor settings

### ISSUE THREAD

**Issue by radeusgd** [VirtusLab/git-machete-intellij-plugin#783]
## Bug description

As in the title, when I open the Machete File Editor to edit it, my global settings for Other File Types are changed to use the tab character. By default, in other files I often edit I need the setting to be off, so whenever I open the machete file the setting changes to an undesirable value and I need to manually change it each time.
I don't think that just opening the dialog should have (permanent) changes to global editor settings.

### Running environment
 - Git Machete plugin version: 1.1.0
 - IDE type: IntelliJ
 - IDE version: 2021.3.1 CE
 - Operating system: Ubuntu 18.04

### Screenshots
![image](https://user-images.githubusercontent.com/1436948/150645110-62e535ab-089a-4ec7-95c9-e58535ce4310.png)

**Comment by PawelLipski** [comment]
Whoops good spot, definitely the setting shouldn't be changed globally... lemme check 🕵🏻

**Comment by PawelLipski** [comment]
For the record, that's a side effect of the fix for https://github.com/VirtusLab/git-machete-intellij-plugin/issues/380... there isn't a separate entry for Code Style of Machete File in Settings.... `com.virtuslab.gitmachete.frontend.file.highlighting.MacheteAnnotator#processIndentationElement` sets up `indentOptions` for `CodeStyleSettings` of `Other File Types`, not `Machete File` ☹️

**Comment by PawelLipski** [comment]
Done! released in v1.2.1
