### ISSUE TITLE
Manipulate `-Xmx` setting in `forkOptions` in CI so that more than 2 workers can run at the same time

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#808]
There's 4GB available... so 3 or even maybe 4 workers should still fit (so we can get rid of `--max-workers=2` in config.yml).

Note that it will be needed to turn off `restore_cache` in CI to actually tests the new behavior.

**Comment by azdrojowa123** [comment]
Finally we decided to change docker resource class ([circleCI-resource-classes](https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes)) from medium plan to _large_, which is currently the most affluent (the most memory and CPU) docker class available on the free plan. This class using more credits per min (20) than previous medium plan. But because git machete-intellij-plugin is open-source project we have 400 000 credits per month on circleCI, which is enough for this class. I conducted a series of tests to find out what number of workers would be optimal, and discovered that best number is around 3/4 workers - it is hard to say certainly, because build time depends on many factors. But 7 workers caused the OOM error to appear
