### ISSUE TITLE
Find a way to systematize where html tags can be placed

### ISSUE THREAD

**Issue by azdrojowa123** [VirtusLab/git-machete-intellij-plugin#884]
Based on problem which occurred during working on https://github.com/VirtusLab/git-machete-intellij-plugin/issues/845 (with an unwanted tag `<br/>`, which occurred there because in certain scenerio the notification was displayed in a different way). 
Best way will be to create some kind of checking if there are no lost html tags in code. 
Script idea: https://github.com/VirtusLab/git-machete-intellij-plugin/blob/master/scripts/enforce-properties-single-quotes-consistent-with-format-elements

**Comment by PawelLipski** [comment]
I'd first expect a full listing of all notification methods used in our codebase, with a spec of what format is expected for which of its params. Then let's think what's the best way of enforcing law & order:
* shell script?
* ArchUnit?
* CheckerFramework (`SubtypingChecker`)?
* AspectJ?

My gut feeling is that the latter is best suited (and we've already got a basic setup for aspects since https://github.com/VirtusLab/git-machete-intellij-plugin/pull/816)
